# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialprice', '0006_smm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smm',
            name='designation',
            field=models.CharField(choices=[('A356', 'A356'), ('A380', 'A380'), ('ADC12', 'ADC12'), ('Zamak3', 'Zamak3'), ('Zamak5', 'Zamak5'), ('Zn99.995', 'Zn99.995')], default='???', max_length=32, verbose_name='牌号'),
        ),
    ]
