# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialprice', '0008_auto_20161123_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smm',
            name='monthnum',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=11, verbose_name='月'),
        ),
        migrations.AlterField(
            model_name='smm',
            name='quarternum',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=4, verbose_name='季'),
        ),
        migrations.AlterField(
            model_name='smm',
            name='yearnum',
            field=models.IntegerField(default=2016, verbose_name='年'),
        ),
        migrations.AlterUniqueTogether(
            name='smm',
            unique_together=set([('designation', 'pricedate')]),
        ),
    ]
